POST http://localhost:4000/v1/register
Content-Type: application/json

{
    "nama": "Fatih Ulil Albab",
    "username": "fatihulil26",
    "email": "Fatihulil@gmail.com",
    "hp": "082257730729",
    "password": "123456aB"
}
###
POST http://localhost:4000/v1/login
Content-Type: application/json

{
    "email": "Fatihulil15@gmail.com",
    "password": "123456aB"
}

###


POST http://localhost:4000/v1/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidWxpbGFsYmFiIiwiaWF0IjoxNjA3MjM0NzYyfQ.QlGrRxcJ7LT5Sdvk4YtPRPgQLt8Wz69TasTPNWxgvbI"
}

###

GET http://localhost:4000/v1/test 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidWxpbGFsYmFiIiwiaWF0IjoxNjA3MjM0NzMxLCJleHAiOjE2MDcyMzQ3NzZ9.qwOk0nARFCe7oVbVATXNcVxyiMRvWha0dSxMML85rmg

###
DELETE  http://localhost:4000/v1/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidWxpbGFsYmFiIiwiaWF0IjoxNjA3MjM0NzYyfQ.QlGrRxcJ7LT5Sdvk4YtPRPgQLt8Wz69TasTPNWxgvbI"
}

###
GET http://localhost:4000/v1/get-website
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidWxpbGFsYmFiIiwiaWF0IjoxNjA3MzExNTYyLCJleHAiOjE2MDczMTI0NjJ9.79rGYDbXJLZW_D2OoZIJ3Lit6Iq80YN86Typ6PiW-aY

{
    "id": "2"
}

###
GET   http://localhost:4000/v1/project/get-project
Content-Type: application/json

###

POST  http://localhost:4000/v1/project/add-project
Content-Type: application/json

{
    "nama": "Project TODOS 2",
    "des": "project personal untuk sandbox",
    "idUser": "11"
}
###

DELETE   http://localhost:4000/v1/project/delete-project
Content-Type: application/json

{
    "id": "2"
}
###

PUT http://localhost:4000/v1/project/update-project
Content-Type: application/json

{
    "id"        : "1",
    "nama"      : "Project TODOS 2",
    "des"       : "project personal untuk sandbox",
    "status"    : "1"
}
###

PUT http://localhost:4000/v1/project/chage-status
Content-Type: application/json

{
    "id"        : "1",
    "status"    : "2"
}
###



### SERVICE TODO ###



###
POST  http://localhost:4000/v1/todo/add-todo
Content-Type: application/json

{
    "projectID": "1",
    "title": "Task 1",
    "des": "Task pertama",
    "doDate" :"",
    "start" :"",
    "end" :"",
    "status" :"1",
    "priority" :"2",

}